apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 10.0.0.0/16
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
  type: LoadBalancer
